### ISSUE TITLE
Design a few options AccessibleAI-Edu logo and share with Arjun and Marija

### ISSUE THREAD

**Issue by mutharasus** [AccessibleAI-edu/accessibleai-edu#10]

**Comment by mutharasus** [comment]
@arjunkunna / @MarijaIgnj , please review the below logo design ideas and let me know if you like any of them. If you have other ideas or other colors etc., Any feedback welcome as this is my very initial attempt. I fully expect this to completely change based on your feedback. Feel free to let me know to go back to the drawing board if you don't like any of these initial attempts.

![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/64eb6ea8-25ea-4ecc-a930-d32b3af2cc11)
![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/88b5d589-5a25-405b-a556-6a7521b7a099)
![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/4cbb65d5-a6cc-408c-8fd1-802e6adfa85c)

**Comment by arjunkunna** [comment]
Thanks Muthu. Marija and I discussed them today. I think option #1 was what we liked best, but Marija will follow up with some specific comments.

**Comment by MarijaIgnj** [comment]
Thanks Muthu for doing this!

As Arjun said, we prefer the first option, but we were just thinking about
trying out different colours. Could you maybe send us a couple of options
with different colours? You can refer to this infographic
<https://drive.google.com/file/d/1iASjTiFQQbMC2zQRMgJQZA9DWhUB0yxn/view?usp=drive_link>
for inspiration.

Best,
Marija

**Comment by mutharasus** [comment]
The colors in the sample PDF you provided were:


![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/19d91dd2-151e-415d-818a-0a6f934ce201)


I modified the logo #1 with the colors from the PDF. These are some of the examples. Please review and provide feedback:


![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/4bdf58b8-5d15-4b1e-b8cb-0fb05a91b6db)
![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/fb838582-1f79-4941-8f5e-5d036f376add)
![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/bd55ac61-d42f-4d60-845b-8213e7cfdbf8)

**Comment by MarijaIgnj** [comment]
@mutharasus Thanks a lot for these! Could you send me a SVG version of the logo so I can play around with colors a bit?

**Comment by mutharasus** [comment]
Attached 2 svg files. One with background and one with transparent background. Let me know if this works. 

![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/f473f924-133b-4e8b-81cb-8adbd3b04491)
![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/17b5b9fb-a919-41b5-9ef9-855d84710f97)

**Comment by MarijaIgnj** [comment]
@mutharasus Great, it works! No worries about the positioning, I am just trying out the colors.

**Comment by MarijaIgnj** [comment]
Hey @arjunkunna @mutharasus I have combined some of these colours and came down to the shortlist of the following two versions:


![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/19a86723-f28f-4744-a469-72410d098281)


You can see how they look like on both white and dark background here. Let me know what you think, I maybe prefer the first one...

P.S. Muthu, I have very slightly changed some of the colours, so it wouldn't too flashy, just so you know for the palette.
