### ISSUE TITLE
Add the new logo and enlarge it to visually fit the page and the navigation menu

### ISSUE THREAD

**Issue by MarijaIgnj** [AccessibleAI-edu/accessibleai-edu#17]

**Comment by mutharasus** [comment]
![AccessibleAI-2xlogo-nobg](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/1c2d53c8-8aba-44d5-ac45-6c480ce79c00)
![AccessibleAI-2xlogo](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/a32cc723-d8b4-4d2e-b7e5-2ef1761e3301)
![AccessibleAI-logo-nobg](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/ce8abe9c-b7ae-4128-9b4c-56c2b671e143)
![AccessibleAI-logo](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/0048aa83-0797-4406-aaf4-6d2a4c88be39)
![AccessibleAI-logo-nobg](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/af8c937c-d5a0-48c8-8462-a3385bffd0f0)
![AccessibleAI-logo](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/134731327/bcb79059-b47e-40d9-aff1-c82a54e84ca8)

**Comment by mutharasus** [comment]
@MarijaIgnj I have uploaded the logo in SVG and PNG versions. Please take a look and let me know if this looks as expected for your needs.

**Comment by MarijaIgnj** [comment]
Can you please make it fit not just in terms of size, but also to be in line with the header? @mutharasus
