### ISSUE TITLE
Set up the In focus slider under the navigation menu

### ISSUE THREAD

**Issue by MarijaIgnj** [AccessibleAI-edu/accessibleai-edu#23]
IN FOCUS slider – with the most recent tutorials, blog posts, news about workshops etc. (it can have 4 most recent posts/uploads). Set it up to enable manual handling of the slider (images, titles etc.)

**Comment by MarijaIgnj** [comment]
@mutharasus It should also be smaller than it is now. You can take this size as a reference: https://bezbednost.org/en/ 

You can also copy the style of this carousel. Each one can have this "In focus" element, a title and an image in the background. Image can also be a little shaded like here.

**Comment by mutharasus** [comment]
The content of the slider needs to be updated. Need to discuss background image situation with @MarijaIgnj. Seems we need 3 different image sizes in some instances to fit all the spots. (Slider, Gallery thumbnail, Tutorial/Blog page)

**Comment by MarijaIgnj** [comment]
@mutharasus this looks good now!
