### ISSUE TITLE
Change icons color and shape (About Accessible AI part on the Index page)

### ISSUE THREAD

**Issue by MarijaIgnj** [AccessibleAI-edu/accessibleai-edu#26]
Colors should be like on the following image (color should be blue on hover as well):

![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/35c6e9cf-a266-49ab-aef2-37db327629b2)

Icon should be:

Vision - eye
Mission - rocket (the one that is there already)
Partner with us - handshake

**Comment by mutharasus** [comment]
@MarijaIgnj  this particular section of the website uses simple icons. So instead of handshake I had to use a different icon. See https://thesabbir.github.io/simple-line-icons/ for reference.

**Comment by MarijaIgnj** [comment]
OK, it's fine like this @mutharasus
