### ISSUE TITLE
Upload articles to Tutorials

### ISSUE THREAD

**Issue by MarijaIgnj** [AccessibleAI-edu/accessibleai-edu#30]
[What is Generative AI](https://docs.google.com/document/d/14fm269lOpjpmJDRdeyfipSWFURilDOLP/edit)
[Generative AI risks](https://docs.google.com/document/d/1KF1zfJ90NPGyDL8b8wNZjM6-UaXvyfY0/edit)

When you click a specific article, it should open the page which contains:

- the cover image from the preview
- the article text
- a PDF button with a PDF of the article that can be downloaded (I do not have designed PDF versions yet, but the button can be made)

**Comment by MarijaIgnj** [comment]
@mutharasus Format the text according to these instructions: 

- **Title**  should be centered and <h2> element
- **Author and date** erased
- **Margin** between the title and the text should be 40px instead of 25px
- Paragraphs should have text align **justify** (I know it is not usually used on websites, but we will used just for these tutorials)
- **Subheadings** should all be the same <h> element, in this case <h3>
- **Subheadings** should have the following format: font-family Poppins, font-size large, font-weight bold and color #9589b7

It should all look like this:

![Tutorial individual page](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/f87beef0-9551-4d84-b895-34ad563977f6)

**Comment by MarijaIgnj** [comment]
Add a Download PDF button and change the share option at the bottom of the page:

![tutorial individual page share and download](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/a53fae17-2a1c-48fb-a7ce-6cf5ba7a8cd8)

The PDF button should be formated like all the other buttons on the website. Share icons should be: like here:

![social share](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/35231bc9-ce22-4b74-9de6-46565be2bdae)

**Comment by MarijaIgnj** [comment]
@mutharasus Go back to the instruction above, a few of them are not done. Also, why is there a link in the title?

**Comment by mutharasus** [comment]
I have now removed the link. I don't think I am able to change the heading to h2 and h3 and have it behave the way you typically expect it to behaving in a HTML due to other overrides that exist. If you need the font to be different size I can make that change. Is there anything else missing now for this?

**Comment by mutharasus** [comment]
Once we have the PDFs we can add the button. I have to update the button to point at the PDF anyway when the PDFs are ready.

**Comment by MarijaIgnj** [comment]
@mutharasus Here are the PDFs:
[what is gen AI pdf.pdf](https://github.com/AccessibleAI-edu/accessibleai-edu/files/12640417/what.is.gen.AI.pdf.pdf)
[gen AI risks.pdf.pdf](https://github.com/AccessibleAI-edu/accessibleai-edu/files/12640418/gen.AI.risks.pdf.pdf)

**Comment by MarijaIgnj** [comment]
> I have now removed the link. I don't think I am able to change the heading to h2 and h3 and have it behave the way you typically expect it to behaving in a HTML due to other overrides that exist. If you need the font to be different size I can make that change. Is there anything else missing now for this?

It is not about how looks, but about SEO. It is necessary for it to be marked as a headline, in order for Google to recognize it as a headline.
