### ISSUE TITLE
Create the website structure according to the following document:

### ISSUE THREAD

**Issue by MarijaIgnj** [AccessibleAI-edu/accessibleai-edu#6]
https://docs.google.com/document/d/157ANEl5UBiVFo_p0l45_D0o5xA7aymPC/edit?usp=sharing&ouid=115579622655359645758&rtpof=true&sd=true

**Comment by mutharasus** [comment]
This looks good

**Comment by mutharasus** [comment]
@arjunkunna please mark the issue to status of "Accepted" if you are all set with this. Then I will mark this issue as closed. Thanks.

**Comment by mutharasus** [comment]
This one is not done. Assigned it to Arjun by mistake.
