### ISSUE TITLE
Add a donate element to the Index page

### ISSUE THREAD

**Issue by MarijaIgnj** [AccessibleAI-edu/accessibleai-edu#62]
We should add a donate slider in the Index page, something like this one at the bottom of the page: https://www.aiforanyone.org/ 

It should contain a DONATE button, an icon (in the style of other ones on the Index page) and a description: 

Support Accessible AI education! Your donation helps us create AI educational materials and host AI 101 workshops. Thank you for helping us empower all those who want to enhance their AI knowledge.

**Comment by MarijaIgnj** [comment]
@mutharasus Here is the code:

<script src="https://donorbox.org/widget.js" paypalExpress="false"></script><iframe src="https://donorbox.org/embed/website-101" name="donorbox" allowpaymentrequest="allowpaymentrequest" seamless="seamless" frameborder="0" scrolling="no" height="900px" width="100%" style="max-width: 500px; min-width: 250px; max-height:none!important"></iframe>

**Comment by MarijaIgnj** [comment]
![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/e17694ed-f1c6-407d-b864-65dca23caa7a)

**Comment by mutharasus** [comment]
@MarijaIgnj  in the screenshot above you can see the instructions are for an "Embedded Donation Form". You're instructions above are to have a DONATE button. Can you provide the instructions and the scripts that go with a DONATE button. It is the 3rd tab in the screenshot.

Thanks.

**Comment by MarijaIgnj** [comment]
@mutharasus Oh right, here you go:

CSS:

<a style="background: #213063 url(https://donorbox.org/images/white_logo.svg) no-repeat 45px;color: #fff;text-decoration: none;font-family: Verdana,sans-serif;display: inline-block;font-size: 16px;padding: 15px 45px;padding-left: 70px;border-radius: 8px;" href="https://donorbox.org/website-101">Donate</a>

PNG:

<a target="_blank" href="https://donorbox.org/website-101"><img src="https://donorbox.org/images/png-donate/logo-button-medium.png" /></a>

<a target="_blank" href="https://donorbox.org/website-101"><img src="https://donorbox.org/images/png-donate/button-medium.png" /></a>



![Image](https://github.com/AccessibleAI-edu/accessibleai-edu/assets/140619642/95cdfc67-dc9e-4fa5-a7fc-3ffcbf719b4b)

**Comment by MarijaIgnj** [comment]
@mutharasus Can you make the donate button smaller, it is huge now.

**Comment by mutharasus** [comment]
Done
